export enum THEMES {
  TRANSPARENT_BORDER = 'TRANSPARENT_BORDER',
  TOP_NAV = 'TOP_NAV',
  INLINE_TRANSPARENT_BORDER = 'INLINE_TRANSPARENT_BORDER',
  INLINE_TOP_NAV = 'INLINE_TOP_NAV',
  NO_PADDING_RIGHT_NO_BOX_TRANSPARENT_BORDER = 'NO_PADDING_RIGHT_NO_BOX_TRANSPARENT_BORDER',
  NO_PADDING_RIGHT_NO_BOX_TOP_NAV = 'NO_PADDING_RIGHT_NO_BOX_TOP_NAV',
  NO_PADDING_LEFT_NO_BOX_TRANSPARENT_BORDER = 'NO_PADDING_LEFT_NO_BOX_TRANSPARENT_BORDER',
  NO_PADDING_LEFT_NO_BOX_TOP_NAV = 'NO_PADDING_LEFT_NO_BOX_TOP_NAV',
}

export const ALLOWED_ARIA_PROPS = ['aria-label', 'aria-labelledby', 'aria-describedby'] as const;
