export const SAMPLE_VARIABLES = [
  {
    name: 'contractorName',
    label: 'Contractor Name',
    tooltip: 'A Contractor\'s legal name, e.g. "John Smith Consulting, LLC"',
    category: 'Consultant / 1099 Contractor Information',
    invalid: true,
    example: 'John Smith Consulting, LLC',
  },
  {
    name: 'contractorFullAddress',
    label: 'Contractor Full Address',
    tooltip:
      'A contractor\'s full address, e.g. "650 Church St. suite 301, San Francisco, CA, 94123"',
    category: 'Consultant / 1099 Contractor Information',
    example: '650 Church St. suite 301, San Francisco, CA, 94123',
  },
  {
    name: 'contractorAddress',
    label: 'Contractor Address',
    tooltip: 'A contractor\'s street address, e.g. "650 Church St. suite 301"',
    category: 'Consultant / 1099 Contractor Information',
    example: '650 Church St. suite 301',
  },
  {
    name: 'contractorCity',
    label: 'Contractor City',
    tooltip: 'A contractor\'s city, e.g. "San Francisco"',
    category: 'Consultant / 1099 Contractor Information',
    is_translatable_variable: true,
    example: 'San Francisco',
  },
  {
    name: 'contractorState',
    label: 'Contractor State',
    tooltip: 'The 2-letter state abbreviation for a contractor\'s state, e.g. "CA"',
    category: 'Consultant / 1099 Contractor Information',
    example: 'CA',
  },
  {
    name: 'contractorZip',
    label: 'Contractor Zip',
    tooltip: 'The postal zip code for a contractor\'s address, e.g. "94114"',
    category: 'Consultant / 1099 Contractor Information',
    example: '94114',
  },
  {
    name: 'contractorProjectDescription',
    label: '1099 Contractor Project Description',
    tooltip:
      'A description of the work to be performed by the contractor, as entered by the hiring manager (a few sentences)',
    category: 'Consultant / 1099 Contractor Information',
    example: 'Developing a new feature for the mobile app',
  },
  {
    name: 'contractorCompensationDescription',
    label: '1099 Contractor Compensation Description',
    tooltip:
      "A description of the compensation and payment terms for the contractor's project (a few sentences)",
    category: 'Consultant / 1099 Contractor Information',
    example: 'Payment of $5000 upon completion of the project',
  },
  {
    name: 'contractorSignature',
    label: 'Contractor Signatory Signature',
    tooltip: 'Indicates where the contractor will sign the agreement',
    category: 'Consultant / 1099 Contractor Information',
    example: 'Signature line for contractor',
  },
  {
    name: 'contractorSignatoryName',
    label: 'Contractor Signatory Name',
    tooltip: 'The full name of the person signing for the contractor, e.g. "James Dean"',
    category: 'Consultant / 1099 Contractor Information',
    example: 'James Dean',
  },
  {
    name: 'contractorSignatoryTitle',
    label: 'Contractor Signatory Title',
    tooltip: 'The title of the person signing for the contractor, e.g. "Chief Executive Officer"',
    category: 'Consultant / 1099 Contractor Information',
    example: 'Chief Executive Officer',
  },
  {
    name: 'contractorSignatureDate',
    label: 'Contractor Signatory Signature Date',
    tooltip: 'The date the contractor signs the agreement, e.g. "09/13/2016"',
    category: 'Consultant / 1099 Contractor Information',
    example: '09/13/2016',
  },
  {
    name: 'businessLegalName',
    label: 'Business legal name',
    tooltip: 'Your company\'s legal name, e.g. "Acme co, Inc."',
    category: 'Company Information',
    isDeprecated: true,
    example: 'Acme co, Inc.',
  },
  {
    name: 'businessDBAName',
    label: 'Business DBA name',
    tooltip: 'Your company\'s fictitious or DBA name, e.g. "Widgets R Us"',
    category: 'Company Information',
    example: '<b>Widgets <br/> R Us</b>',
  },
  {
    name: 'businessFullAddress',
    label: 'Business full address',
    tooltip:
      'The full address for your company\'s primary work location,\n      e.g. "123 Market Street, Suite 402, San Francisco, CA, 94123"',
    category: 'Company Information',
    example: '123 Market Street, Suite 402, San Francisco, CA, 94123',
  },
  {
    name: 'businessStreetAddress',
    label: 'Business street address',
    tooltip:
      'The street address for your company\'s primary work location, e.g. "123 Market Street, Suite 402"',
    category: 'Company Information',
    example: '123 Market Street, Suite 402',
  },
  {
    name: 'businessCity',
    label: 'Business City',
    tooltip: 'The city for your company\'s primary work location, e.g. "San Francisco"',
    category: 'Company Information',
    example: 'San Francisco',
  },
  {
    name: 'businessState',
    label: 'Business State',
    tooltip: 'The 2-letter state abbreviation for your company\'s primary work location, e.g. "CA"',
    category: 'Company Information',
    example: 'CA',
  },
  {
    name: 'businessZip',
    label: 'Business Zip',
    tooltip: 'The postal zip code for your company\'s primary work location, e.g. "94110"',
    category: 'Company Information',
    example: '94110',
  },
  {
    name: 'startDate',
    label: 'Start date',
    tooltip: 'An employee\'s hire date, e.g. "09/21/2016"',
    category: 'Employment Information',
    example: '09/21/2016',
  },
  {
    name: 'endDate',
    label: 'End date',
    tooltip: 'An employee\'s last day of work (used for temporary employees), e.g. "08/31/2017"',
    category: 'Employment Information',
    example: '08/31/2017',
  },
  {
    name: 'employeeTitle',
    label: 'Title',
    tooltip: 'An employee\'s title, e.g. "Senior Account Executive"',
    category: 'Employment Information',
    example: 'Senior Account Executive',
  },
  {
    name: 'department',
    label: 'Department',
    tooltip: 'The employee\'s department, e.g. "Sales"',
    category: 'Employment Information',
    example: 'Sales',
  },
  {
    name: 'managerName',
    label: 'Manager Name',
    tooltip: 'An employee\'s manager\'s full name, e.g. "Jane Doe"',
    category: 'Employment Information',
    example: 'Jane Doe',
  },
  {
    name: 'managerTitle',
    label: 'Manager Title',
    tooltip: 'An employee\'s manager\'s title, e.g. "West Coast Sales Director"',
    category: 'Employment Information',
    example: 'West Coast Sales Director',
  },
  {
    name: 'weeklyHours',
    label: 'Standard weekly hours',
    tooltip: 'Expected weekly hours for an employee, e.g. "40"',
    category: 'Employment Information',
    example: '40',
  },
  {
    name: 'payFrequency',
    label: 'Pay frequency',
    tooltip: 'Pay frequency for this employee, e.g. "semi-monthly"',
    category: 'Employment Information',
    example: 'semi-monthly',
  },
  {
    name: 'locationName',
    label: 'Work location name',
    tooltip: 'The name of the employee\'s work location, e.g. "San Francisco office"',
    category: 'Employment Information',
    example: 'San Francisco office',
  },
  {
    name: 'locationFullAddress',
    label: 'Work location address',
    tooltip:
      'The full address of the employee\'s work location, e.g. "123 Market Street, San Francisco, CA, 94110"',
    category: 'Employment Information',
    example: '123 Market Street, San Francisco, CA, 94110',
  },
  {
    name: 'locationAddress',
    label: 'Work location address',
    tooltip: 'The street address of the employee\'s work location, e.g. "123 Market Street"',
    category: 'Employment Information',
    example: '123 Market Street',
  },
  {
    name: 'locationCity',
    label: 'Work location city',
    tooltip: 'The city of the employee\'s work location, e.g. "San Francisco"',
    category: 'Employment Information',
    example: 'San Francisco',
  },
  {
    name: 'specifiedSalary',
    label: 'Compensation',
    tooltip: "Descriptive compensation including the pay unit, e.g. '$60,000 per year.' ",
    category: 'Compensation',
    example: '$60,000 per year',
  },
  {
    name: 'yearlySalary',
    label: 'Annual Salary',
    tooltip: 'The employee\'s annual salary, e.g. "$60,000"',
    category: 'Compensation',
    example: '$60,000',
  },
  {
    name: 'monthlySalary',
    label: 'Monthly Salary',
    tooltip: 'The employee\'s monthly salary, e.g. "$5,000"',
    category: 'Compensation',
    example: '$5,000',
  },
  {
    name: 'weeklySalary',
    label: 'Weekly Salary',
    tooltip: 'The employee\'s weekly salary, e.g. "$1000"',
    category: 'Compensation',
    example: '$1000',
  },
  {
    name: 'hourlySalary',
    label: 'Hourly Wage',
    tooltip: 'The employee\'s hourly wage, e.g. "$15"',
    category: 'Compensation',
    example: '$15',
  },
  {
    name: 'targetAnnualBonus',
    label: 'Target annual bonus dollars',
    tooltip:
      'The employee\'s target annual bonus in dollars, as entered by the hiring manager, e.g. "$15,000"',
    category: 'Compensation',
    example: '$15,000',
  },
  {
    name: 'targetAnnualBonusPercent',
    label: 'Target annual bonus percentage',
    tooltip:
      'The employee\'s target annual bonus in percent, as entered by the hiring manager, e.g. "25%"',
    category: 'Compensation',
    example: '25%',
  },
  {
    name: 'signingBonus',
    label: 'Signing bonus',
    tooltip:
      'The amount of the employee\'s signing bonus, as entered by the hiring manager, e.g. "$7,000"',
    category: 'Compensation',
    example: '$7,000',
  },
  {
    name: 'onTargetCommission',
    label: 'On-target commission',
    tooltip:
      'The amount, in dollars, of an employee\'s on-target commission, as entered by the hiring manager, e.g. "$3,000"',
    category: 'Compensation',
    example: '$3,000',
  },
  {
    name: 'relocationReimbursement',
    label: 'Relocation reimbursement',
    tooltip:
      'The amount, in dollars, of an employee\'s relocation\n      reimbursement as entered by the hiring manager, e.g. "$6,000"',
    category: 'Compensation',
    example: '$6,000',
  },
  {
    name: 'overtimeRate',
    label: 'Overtime rate',
    tooltip: 'The increase in hourly wage when an employee is working overtime, e.g. "1.5 X"',
    category: 'Compensation',
    example: '1.5 X',
  },
  {
    name: 'equityNumShares',
    label: 'Number of shares',
    tooltip: 'The number of shares an employee is receiving in a stock grant, e.g. "500"',
    category: 'Equity',
    example: '500',
  },
  {
    name: 'createdAt',
    label: "Today's date",
    tooltip: 'The date the document is sent to the employee, e.g. "09/19/2016"',
    category: 'Dates',
    example: '09/19/2016',
  },
  {
    name: 'expirationDate',
    label: 'Offer expiration date',
    tooltip: 'The date the offer expires if still unsigned, e.g. "09/16/2016"',
    category: 'Dates',
    example: '09/16/2016',
  },
  {
    name: 'companySignature',
    label: 'Company signatory signature',
    tooltip: 'The signature of the company exec signing this document.',
    category: 'Signature',
    example: 'Signature line for company exec',
  },
  {
    name: 'companySignatureDate',
    label: 'Company signatory date signed',
    tooltip: 'The date the document is sent to the employee, e.g. "09/13/2016"',
    category: 'Signature',
    example: '09/13/2016',
  },
  {
    name: 'companySignatoryName',
    label: 'Company signatory name',
    tooltip: 'The full name of the company exec signing this document, e.g. "Michael Jones"',
    category: 'Signature',
    example: 'Michael Jones',
  },
  {
    name: 'companySignatoryTitle',
    label: 'Company signatory title',
    tooltip: 'The title of the company exec signing this document, e.g. "Chief Executive Officer"',
    category: 'Signature',
    example: 'Chief Executive Officer',
  },
  {
    name: 'employeeSignature',
    label: 'Employee signature',
    tooltip: 'Indicates where the employee should sign the agreement',
    category: 'Signature',
    example: 'Signature line for employee',
  },
  {
    name: 'employeeSignatureDate',
    label: 'Employee signature date',
    tooltip: 'The date the employee signs the agreement, e.g. "09/15/2016"',
    category: 'Signature',
    example: '09/15/2016',
  },
  {
    name: 'SeveranceSignature',
    label: 'Severance signatory signature',
    tooltip: 'The signature of the company exec signing severance document.',
    category: 'Signature',
    example: 'Signature line for severance',
  },
  {
    name: 'SeveranceSignatureDate',
    label: 'Severance agreement date signed',
    tooltip: 'The date the document is sent to the employee, e.g. "09/13/2016"',
    category: 'Signature',
    example: '09/13/2016',
  },
  {
    name: 'SeveranceSignatoryName',
    label: 'Severance signatory name',
    tooltip: 'The full name of the company exec signing severance document, e.g. "Richard James"',
    category: 'Signature',
    example: 'Richard James',
  },
  {
    name: 'SeveranceSignatoryTitle',
    label: 'Severance signatory title',
    tooltip:
      'The title of the company exec signing severance document, e.g. "Chief Technical Officer"',
    category: 'Signature',
    example: 'Chief Technical Officer',
  },
  {
    name: 'contractorPersonalEmail',
    label: 'Personal Email',
    tooltip: 'The personal email of a contractor, e.g. "susan_95@gmail.com"',
    category: 'Consultant / 1099 Contractor Information',
    example: 'susan_95@gmail.com',
  },
  {
    name: 'locationState',
    label: 'Work location state',
    tooltip: 'The state of the employee\'s work location, e.g. "California"',
    category: 'Employment Information',
    example: 'California',
  },
  {
    name: 'cobraEligibilityDate',
    label: 'Federal COBRA Eligibility Date',
    tooltip: '',
    category: 'Insurance',
    example: '01/01/2023',
  },
  {
    name: 'partTimeEmployees',
    label: 'Part Time Employees Count',
    tooltip: '',
    category: 'Insurance',
    example: '10',
  },
  {
    name: 'fullTimeEmployees',
    label: 'Full Time Employees Count',
    tooltip: '',
    category: 'Insurance',
    example: '50',
  },
  {
    name: 'companyFein',
    label: 'The Fein for the business',
    tooltip: 'The FEIN identity for the employement which is a 9 digit identifier for a company.',
    category: 'Company Information',
    example: '12-3456789',
  },
  {
    name: 'managerEmail',
    label: "Manager's Work Email",
    tooltip: "An employee's manager's work email",
    category: 'Employment Information',
    example: 'manager@example.com',
  },
  {
    name: 'primaryEmail',
    label: 'Company Email',
    tooltip: "Your company's primary email address",
    category: 'Company Information',
    example: 'info@company.com',
  },
  {
    name: 'lastRevisedAt',
    label: 'Last revised date for the notice',
    tooltip: '',
    category: 'Notice',
    example: '01/01/2023',
  },
  {
    name: 'personalLeave',
    label: 'Personal Leave days per year',
    tooltip: 'Number of personal leave days per year, e.g. "15"',
    category: 'Employment Information',
    example: '15',
  },
  {
    name: '5e82d4c1a04dd7689e18f603',
    label: 'Area living in NY',
    category: 'Custom Information',
    example: 'Brooklyn',
  },
  {
    name: '5e82d4c37c49d73efa1302ae',
    label: 'Food preference',
    category: 'Custom Information',
    example: 'Vegetarian',
  },
  {
    name: 'customInfo',
    label: 'Custom Information',
    tooltip: 'The custom information you store while onboarding the employees.',
    category: 'Custom Information',
    example: 'Custom data specific to the employee',
  },
];
